# Generated by Django 5.1.3 on 2024-11-09 03:56

import django.utils.timezone
import sala_leitura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_leitura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prev',
            field=models.DateField(default=sala_leitura.models.data_devolucao_default),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
