# Generated by Django 5.1.3 on 2024-11-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_leitura', '0009_alter_livro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
