# Generated by Django 5.1.3 on 2024-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_leitura', '0003_alter_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True),
        ),
        migrations.AlterField(
            model_name='editora',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True),
        ),
        migrations.AlterField(
            model_name='editora',
            name='fone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tombo',
            field=models.DateTimeField(),
        ),
    ]
