# Generated by Django 5.1.3 on 2024-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_leitura', '0010_alter_livro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='tombo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
