# Generated by Django 5.1.3 on 2024-11-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_leitura', '0011_alter_livro_tombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='colecao',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='livro',
            name='procedencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
