# Generated by Django 3.0 on 2024-11-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('id_acesso', models.AutoField(primary_key=True, serialize=False)),
                ('acesso', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('id_unidade', models.IntegerField()),
                ('master', models.BooleanField(blank=True, null=True)),
                ('incluir', models.BooleanField(blank=True, null=True)),
                ('alterar', models.BooleanField(blank=True, null=True)),
                ('imprimir', models.BooleanField(blank=True, null=True)),
                ('excluir', models.BooleanField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acessos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='Id_cliente', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('nome_social', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
                ('cpf', models.CharField(blank=True, max_length=18, null=True)),
                ('ie_rg', models.CharField(blank=True, max_length=25, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('ddd', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('ra', models.CharField(blank=True, max_length=5, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id_editora', models.AutoField(db_column='Id_Editora', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('ddd', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('ult_alteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Editora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unidade', models.CharField(blank=True, max_length=2, null=True)),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('id_operacao', models.IntegerField(blank=True, null=True)),
                ('destinatario', models.CharField(blank=True, db_column='Destinatario', max_length=40, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('id_unidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kardex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KardexOperacao',
            fields=[
                ('id_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('entrada', models.BooleanField(blank=True, null=True)),
                ('saida', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kardex_operacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id_locacao', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('emissao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('reserva', models.BooleanField(blank=True, db_column='Reserva', null=True)),
                ('confirma', models.BooleanField(blank=True, db_column='Confirma', null=True)),
                ('liquida', models.BooleanField(blank=True, db_column='Liquida', null=True)),
            ],
            options={
                'db_table': 'Locacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocacaoItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_locaitens', models.IntegerField(blank=True, null=True)),
                ('id_locacao', models.IntegerField(blank=True, null=True)),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('dev_prevista_ori', models.DateTimeField(blank=True, null=True)),
                ('renovou', models.IntegerField(blank=True, null=True)),
                ('dev_prevista', models.DateTimeField(blank=True, null=True)),
                ('dev_realizada', models.DateTimeField(blank=True, null=True)),
                ('devolvido', models.BooleanField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Locacao_itens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('tombo', models.DateTimeField(blank=True, null=True)),
                ('numero_tombo', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_de_barras', models.CharField(blank=True, max_length=13, null=True)),
                ('autor', models.CharField(blank=True, db_column='Autor', max_length=120, null=True)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('procedencia', models.CharField(blank=True, db_column='Procedencia', max_length=120, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('local_estoque', models.CharField(blank=True, max_length=30, null=True)),
                ('id_editora', models.IntegerField(blank=True, db_column='id_Editora', null=True)),
                ('colecao', models.CharField(blank=True, max_length=120, null=True)),
                ('edicao', models.CharField(blank=True, max_length=20, null=True)),
                ('volume', models.CharField(blank=True, db_column='Volume', max_length=20, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('id_tipo_produto', models.IntegerField(blank=True, null=True)),
                ('defeito', models.BooleanField(blank=True, null=True)),
                ('bloquear', models.BooleanField(blank=True, null=True)),
                ('aquisicao_c', models.BooleanField(blank=True, db_column='Aquisicao_c', null=True)),
                ('aquisicao_d', models.BooleanField(blank=True, db_column='Aquisicao_d', null=True)),
                ('aquisicao_t', models.BooleanField(blank=True, db_column='Aquisicao_t', null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('ult_alteracao', models.DateTimeField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id_tipo_produto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=10)),
                ('id_unidade', models.IntegerField()),
                ('id_acesso', models.IntegerField()),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
